### ISSUE TITLE
tensorflow model convert to keras model

### ISSUE THREAD

**Issue by zoeysgithub** [titu1994/MobileNetworks#10]
hello,
if i load the tensorflow model " MobileNet_v1_0.25_128 ",i just need to model = MobileNet((128, 128, 3), alpha=0.5, weights=None) ?

**Comment by titu1994** [comment]
Correct, but If you want the pretrained weights, then you should set weights="imagenet".

**Comment by zoeysgithub** [comment]
thank you for reply!`
iif alpha=0.25,the weights should set "imagenet"?
edit to model = MobileNets((128, 128, 3), alpha=0.25, weights="imagenet")?

**Comment by titu1994** [comment]
Yup
