### ISSUE TITLE
Question about output_stride

### ISSUE THREAD

**Issue by mrlzla** [titu1994/MobileNetworks#11]
Hello. Amazing work! But I have a question.
As we can see [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.py) is a mobilenet version on tensorflow. They use really advanced ( ;) ) param output stride in order to set output size n*x lower than input. They use dilation_rate in separable_conv to achive this. Is there some advanced param in this version of the network?)

**Comment by titu1994** [comment]
Hmm. If I remember correctly, that portion of the code never gets called. I think it's fine not to include it, since the current model can correctly load the weights from TF and can provide correct predictions.

**Comment by mrlzla** [comment]
I forgot about the issue, sorry ;)
But if I want to use this model as feature extractor into another model it will be good solution to add output_stride as param of model
