### ISSUE TITLE
Error when loading no_top weights 

### ISSUE THREAD

**Issue by iamrosmarin** [titu1994/MobileNetworks#2]
Hi @titu1994 ,

Congrats for your amazing work done.

I'm getting some errors while loading the weights with no_top:
`"Unable to open object (Object 'reshape_1' doesn't exist)"`

It seems the last five layers hasn't been correctly delated from the original weights file in [create_no_top.py](https://github.com/titu1994/MobileNetworks/blob/master/weights/create_no_top.py#L15) .

Hope you can help me! 

Thanks!

**Comment by titu1994** [comment]
What are the parameters with which you are fine tuning ?

**Comment by iamrosmarin** [comment]
I'm creating the MobileNets model for a binary classification problem: 
`model = MobileNets(input_shape=(224, 224, 3), alpha=1.0, depth_multiplier=1,
                dropout=1e-3, include_top=False, weights='imagenet',
                 input_tensor=None, pooling=None, classes=2)`
And I get the error at the point of loading weights with no top:

**Comment by titu1994** [comment]
Yes that was my mistake. I dropped the weight layers but forgot to remove the layer names from the layer_names attribute which tells keras which weight layers to load.

To get it working, go to ~/.keras/models/ and delete the mobilenet_1_0_224_tf_no_top.h5 file, and then run your program again. It will download the updated weight file now and work correctly.
