### ISSUE TITLE
AttributeError: 'module' object has no attribute 'depthwise_conv2d'

### ISSUE THREAD

**Issue by levelvc** [titu1994/MobileNetworks#4]
Hi @titu1994, getting this issue:

`AttributeError: 'module' object has no attribute 'depthwise_conv2d'`

Keras backend does not have that function in latest.

**Comment by titu1994** [comment]
Sorry about that. Forgot that Keras 2.0.5 doesn't support K.depthwise_conv2d(...) yet. Fixed it in a temporary commit.

Btw, this code was merged into Keras master so you can now directly load all MobileNet models with weights right from `keras.applications.mobilenet` from master, or wait for another release of Keras.
