### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Zumbalamambo** [titu1994/MobileNetworks#8]
It throws the following error while running predict_image

`TypeError: depthwise_conv2d() got an unexpected keyword argument 'data_format'`

**Comment by titu1994** [comment]
Could you provide the entire debug log ?

**Comment by Zumbalamambo** [comment]
okay thank you. I have fixed it by updating it to the latest version of keras

**Comment by Yuvarajganesh112** [comment]
I have the same problem even after I upgraded keras
