### ISSUE TITLE
Training a custom classifier

### ISSUE THREAD

**Issue by Zumbalamambo** [titu1994/MobileNetworks#9]
I have two folders namely "Male", "Female" which contains genderwise pics.

How do i load those pics, train my model and create a model file with mobilenet ?

**Comment by Zumbalamambo** [comment]
already I have trained it with inception and I have the model (.pb) file. It is too slow

**Comment by titu1994** [comment]
If you want to use pure Tensorflow without Keras, then the same steps you used with Inception should be possible with TF-Slim for MobileNets. 

For Keras, you can load the weights of one of the variants, add a final dense layer and use include_top=False to train a MobileNet on your dataset (see the Keras blogpost about fine-tuning) - https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html

**Comment by Zumbalamambo** [comment]
can you please give me an example for the same ?
